name: test

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@master
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: node_modules
      - run: pnpm install
      - run: pnpm build
